import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";

import styles from "./page.module.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className={styles.nav}>
          <div className={styles.navContent}>
            <Link href="/">
              <p className={styles.nextPageText}>Formulario</p>
            </Link>
            <Link href="/tasks">
              <p className={styles.nextPageText}>Tareas</p>
            </Link>
            <Link href="/history">
              <p className={styles.nextPageText}>Historial</p>
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
